import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

// Import global styles
import './index.css';

// Import Amplify and the UI component styles
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';

// Import the configuration file generated by the sandbox
import outputs from '../amplify_outputs.json';

// Configure Amplify with your backend details
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
