import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

// Import global styles
import './index.css';

// Import Amplify and the UI component styles
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';

// Configure Amplify with your backend details
try {
  // Import the configuration file generated by the sandbox
  const outputs = await import('../amplify_outputs.json');
  Amplify.configure(outputs.default || outputs);
  console.log('Amplify configured successfully');
} catch (error) {
  console.error('Failed to configure Amplify:', error);
  console.warn('Run "npx ampx sandbox" to deploy your backend first');
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);